### ISSUE TITLE
Unable to read QR Code

### ISSUE THREAD

**Issue by idoodler** [marvinsxtr/covidpass#6]
First of all, nice App :)

The Website can't ready my QR Code, I tried the full document, just the QR code with or without a flash. All Using the iPads Files App Scan Document Feature, I also tried to directly photograph the QR Code with my iPhone. Nothing worked:/

Same on my MacBook with Chrome or Safari.

I have a genuine EU COVID-19 Vaccination Certificate created by a local Pharmacy in Germany. My name has a Umlauts like `ö` and `ä` in it. May this be the issue?

I trued to check on any error logs, but nothing in the Web Console.

PS: I tried both the first and second vaccination certificate separate and combined in one PDF

**Comment by stereonom** [comment]
I also have an umlaut in my surname.

I loaded the scanned QR-Code into PhotoShop and made it as sharp as i could. No chance.

**Comment by idoodler** [comment]
I just took a screenshot from the German Corona-Warn App, converted it to a PDF and it worked. I guess the QR-Code reader is very sensitive.
